server:
  port: 8090

spring:
  application:
    name: User-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
