spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # or your preferred value (e.g., validate, create, create-drop)
    show-sql: true # Set to true to enable SQL logging

server:
  port: 8091 # Port on which the Spring Boot application will run

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
