spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myusername
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # or your preferred value (e.g., validate, create, create-drop)
    show-sql: true # Set to true to enable SQL logging

server:
  port: 8091 # Port on which the Spring Boot application will run


